import AppKit
@testable import MlxVoice_Debug
import XCTest

// The temporary clipboard write used to drive synthetic Cmd+V must be tagged so clipboard
// managers exclude it from history. It is restored immediately and is not user-copied content.
final class TypingServiceTransientPasteboardTests: XCTestCase {

    func testTransientPasteboardItem_carriesText() {
        let item = TypingService.makeTransientPasteboardItem("hello world")
        XCTAssertEqual(
            item.string(forType: .string),
            "hello world",
            "the plain string must survive so paste and clipboard restore behave unchanged"
        )
    }

    func testTransientPasteboardItem_isMarkedForClipboardManagers() {
        let item = TypingService.makeTransientPasteboardItem("hello world")
        let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let types = item.types.map(\.rawValue)
        XCTAssertTrue(
            types.contains(transientType.rawValue),
            "temporary write must be marked Transient so clipboard managers skip it"
        )
        XCTAssertTrue(
            types.contains(autoGeneratedType.rawValue),
            "temporary write must be marked AutoGenerated so clipboard managers skip it"
        )
        XCTAssertEqual(
            item.data(forType: transientType)?.count,
            0
        )
        XCTAssertEqual(
            item.data(forType: autoGeneratedType)?.count,
            0
        )
    }

    func testTransientMarkersSurvivePasteboardWrite() throws {
        let name = NSPasteboard.Name("com.fluidvoice.tests.transient.\(UUID().uuidString)")
        let pasteboard = NSPasteboard(name: name)
        defer { pasteboard.releaseGlobally() }

        pasteboard.clearContents()
        XCTAssertTrue(
            pasteboard.writeObjects([TypingService.makeTransientPasteboardItem("hello world")])
        )

        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertEqual(item.string(forType: .string), "hello world")
        XCTAssertTrue(types.contains("org.nspasteboard.TransientType"))
        XCTAssertTrue(types.contains("org.nspasteboard.AutoGeneratedType"))
    }

    func testTransientPasteboardItem_isNotMarkedConcealed() {
        let item = TypingService.makeTransientPasteboardItem("hello world")
        let types = item.types.map(\.rawValue)
        XCTAssertFalse(
            types.contains("org.nspasteboard.ConcealedType"),
            "ConcealedType signals sensitive content and must not be applied to a transcript"
        )
    }

    func testFocusRestoreDoesNotRaiseAllWindowsOfTargetApp() {
        // Issue #748: restoring focus after dictation must NOT raise every window of the
        // target app. `.activateAllWindows` brings forward all windows of the process and
        // destroys a multi-window layout (e.g. WebStorm) on every dictation.
        let options = TypingService.focusRestoreActivationOptions

        XCTAssertTrue(
            options.contains(.activateIgnoringOtherApps),
            "focus restore must still activate the target app and bring it forward"
        )
        XCTAssertFalse(
            options.contains(.activateAllWindows),
            "Restoring focus must not raise every window of the target app (issue #748)"
        )
    }
}
